### PR TITLE
Delete and Update actions + Refactor

### PR DESCRIPTION
**Pull request by ihor-sokoliuk**
Added Delete and Update record actions to the library (in the end of the code changes).

Additionally, I formatted the scripts with a Black formatter.

### CODE REVIEW

**Comment by ihor-sokoliuk** [comment]
@infeeeee feel free to review

**Comment by infeeeee** [comment]
Nice, I liked the `delete_records` method, why did you remove it? Cloud noco has some very strict rate limiting, it would be useful to delete a lot of records in a single call. It's just a list comprehension, I will do it.

**Comment by infeeeee** [comment]
Messed up branches I will change some things

**Comment by infeeeee** [comment]
But thanks!

**Pull request merged**
